parameters:
#    crm_producto.example.class: Crm\ProductoBundle\Example

services:
#    crm_producto.example:
#        class: %crm_producto.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
